[build]
default-target = "aarch64-unknown-linux-gnu"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH",
    # Add GLIBC and libstdc++ installation steps
    "apt-get --assume-yes install libc6-dev:$CROSS_DEB_ARCH",
    "apt-get --assume-yes install libstdc++6:$CROSS_DEB_ARCH",
]
